# Generated by Django 3.2.19 on 2024-09-04 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0002_rename_question_text_question_question'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='question',
            new_name='question_text',
        ),
    ]
