# Generated by Django 3.2.19 on 2024-09-04 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0003_rename_question_question_question_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='question_text',
            new_name='questions',
        ),
    ]
