# Generated by Django 3.2.19 on 2024-09-04 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0004_rename_question_text_question_questions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='questions',
            new_name='question',
        ),
    ]
